print("---------------------------------------")
print()
print("|x = 35                               |")
print()
print("|                                     |")
print()
print("|                x = 35               |")
print()
print("|                                     |")
print()
print("|                               x = 35|")
print()
print("---------------------------------------")
